name: Update gist with WakaTime summary
on:
  schedule:
    - cron: '40 1 * * *'
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    # Specify the environment name to use
    environment: name-of-your-environment
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: jasonzysun/wakatime-sync@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID}}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SCU_KEY: ${{ secrets.SCU_KEY }}
